<?xml version="1.0" encoding="utf-8"?><workItemType dslVersion="12.0.0.0" Name="Issue" source="F:\Teste\mto_process\MTO Software Factory Process Template\WorkItem Tracking\TypeDefinitions\Issue.xml" xmlns="http://schemas.microsoft.com/dsltools/WITDesigner" />